export const Post = [
    {
        id: 1,
        category:"Fashion",
        avatar:'M',
        title: "A Loving Heart is the Truest Wisdom",
        subheader: "Crypto collectibles and NFT’s are gaining steam",
        image: "https://life-saver.site/wp-content/uploads/2021/02/image-31.png",
        cartContent: "Crypto collectibles and NFT’s are gaining steam, creating a newfound wealth to its creators and early buyers. Learn how you can earn too from digital collectibles that could be valued substantially higher in the next two years.",
        content:"People love uniqueness. You can tell that’s so because if there’s only one example of something in the whole world then someone, somewhere will be willing to pay a lot for it, and much more than they would compared to if it had been mass-produced. First editions of books, postage stamps, art, memorabilia from famous names, all of it can fetch high prices",        
    },
    {
        id: 2,
        category:"Technology",
        avatar:'A',
        title: "5 Best Coupon Websites to Save You Tons of Money in 2021",
        subheader: "If you shop online, you probably know the fantastic",
        image: "https://life-saver.site/wp-content/uploads/2021/02/image-21.png",
        cartContent: "If you shop online, you probably know the fantastic feeling of typing a coupon code and scoring astonishing discounts on your steals. Thanks to these five coupon websites we’ve collected for you, you can now save up to 90% on clothes, food, home appliances, and just about anything!",
        content:"We live in the magnificent age of not paying full prices. And thanks to online shopping and coupons, getting up to 90% off your cart is just one promo code away. You just have to know where to look.",        
    },
    {
        id: 3,
        category:"Travel",
        avatar:'C',
        title: "6 Creative (and Legit) Ways to Make an Extra Income",
        subheader: "The world of employment has changed for good",
        image: "https://life-saver.site/wp-content/uploads/2021/02/image.jpg",
        cartContent: "The world of employment has changed for good. Gone are the days when your boss demanded that you show up at 9 am sharp and “drop your pen” no later than 18:01. These days, work from home is so common—it became 2020’s most trending hashtag.",
        content:"Online-savvy people worldwide are taking advantage of this new situation and embark on brand new virtual careers that generate much more than a few extra bucks. And they are not smarter or more talented than the average Joe. They simply learned to grab the low-hanging online fruits available out there for people like you and me.",        
    },
    {
        id: 4,
        category:"Food",
        avatar:'F',
        title: "5 Foods That Help You Lose Weight",
        subheader: "Fat isn’t fate, although it can sometimes feel like it’s your destiny to pile on the pounds as you get older. ",
        image: "https://life-saver.site/wp-content/uploads/2021/02/image-16.png",
        cartContent: "Fat isn’t fate, although it can sometimes feel like it’s your destiny to pile on the pounds as you get older. You may have come to believe that ageing makes weight gain inevitable, but it doesn’t have to be that way. ",
        content:"No, we’re not going to tell you to do loads of exercise, because exercise isn’t as efficient at keeping weight off as you might think. It is definitely good for your health, and it is worthwhile, but the study reveals that it was only part of the equation. The other key points are reducing your intake of certain foods, getting 6 to 8 hours of sleep every night and not sitting in front of a screen quite so much.",        
    },
    {
        id: 5,
        category:"Photography",
        avatar:'H',
        title: "Top Investments of the Last Decade",
        subheader: "From Gold to Cannabis to Bitcoin, here are the top investments",
        image: "https://life-saver.site/wp-content/uploads/2021/02/image.png",
        cartContent: "From Gold to Cannabis to Bitcoin, here are the top investments that made Canada an economic powerhouse and an inspiration to the whole world. What is the number one money-maker? Teaser: Big banks don’t want you to know about this lucrative investment.",
        content:"Canada’s Cannabusiness took a surprising turn in 2018 as the country legislated its Marijuana laws. Aurora Cannabis was there to lead the way and profit. With its record-breaking stock price as its currency, Aurora went shopping, buying smaller players, scaling its medical marijuana business while establishing a footprint in the expanding recreational market, effectively coining the term Green Gold.",        
    },
]